# ANN

## Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Combining training files

In [2]:
dataset_train = pd.read_csv(r'data/reddit-train.csv')
dataset_test = pd.read_csv('data/reddit-test.csv')
frames = [dataset_train, dataset_test]
dataset = pd.concat(frames)

## Isolating Independent & Dependent Variables

In [3]:
X = dataset.iloc[:, 7:]
subreddits = np.array(dataset.iloc[:, 0])
X['subreddits'] = subreddits
y = dataset.iloc[:, dataset.columns == 'label'].values

## Encoding subreddits

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

## Splitting into training and test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [6]:
print(y_test)

[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]


## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Training Artificial Neural Network

Inititalizing the ANN

In [8]:
import tensorflow as tf
ann = tf.keras.models.Sequential()

Adding First and Second Hidden Layers

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compiling and training the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 150)

Epoch 1/100
89/89 [==============================] - 0s 680us/step - loss: 0.6946 - accuracy: 0.5471
Epoch 2/100
89/89 [==============================] - 0s 646us/step - loss: 0.6250 - accuracy: 0.6654
Epoch 3/100
89/89 [==============================] - 0s 680us/step - loss: 0.5425 - accuracy: 0.7294
Epoch 4/100
89/89 [==============================] - 0s 691us/step - loss: 0.4984 - accuracy: 0.7548
Epoch 5/100
89/89 [==============================] - 0s 657us/step - loss: 0.4763 - accuracy: 0.7678
Epoch 6/100
89/89 [==============================] - 0s 680us/step - loss: 0.4599 - accuracy: 0.7776
Epoch 7/100
89/89 [==============================] - 0s 669us/step - loss: 0.4477 - accuracy: 0.7896
Epoch 8/100
89/89 [==============================] - 0s 657us/step - loss: 0.4372 - accuracy: 0.7980
Epoch 9/100
89/89 [==============================] - 0s 657us/step - loss: 0.4290 - accuracy: 0.8054
Epoch 10/100
89/89 [==============================] - 0s 737us/step - loss: 0.4202 - accura

## Predicting Test Set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 0]
 ...
 [1 0]
 [0 0]
 [0 0]]


## Check Accuracy using Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[230  95]
 [103 283]]


0.7215189873417721